---
title: "Bridges"
output: github_document
---

```{r}
#Importing Data
library(readr)
temp <- tempfile()
download.file("https://www.fhwa.dot.gov/bridge/nbi/2018hwybronefiledel.zip",temp)
data <- read_delim(unz(temp, "2018HwyBridgesDelimitedAllStates.txt"), ",", col_names = T)
unlink(temp)
```

```{r}
#Subsetting to make smaller dataset with variables of interest

myvars <- c("STATE_CODE_001", "STRUCTURE_NUMBER_008", "COUNTY_CODE_003", "ROUTE_PREFIX_005B", "SERVICE_LEVEL_005C", "MAINTENANCE_021", "YEAR_BUILT_027", "ADT_029", "HISTORY_037", "DECK_COND_058", "SUPERSTRUCTURE_COND_059", "CHANNEL_COND_061")
subset <- data[myvars]
names <- c("statecode", "structure.number", "countycode", "route.prefix", "service.level", "maintenance.responsibility", "yearbuilt", "avg.daily.traffic", "historical.significance", "deck.condition", "superstructure.condition", "channel.condition")
names(subset) <- names
```

```{r}
subset$superstructure.condition <- as.numeric(as.character(subset$superstructure.condition))
subset$avg.daily.traffic <- as.numeric(as.character(subset$avg.daily.traffic))
str(subset)
```

```{r}
#Investigating Bridges with conditions labeled "poor" (4) or below
library(ggplot2)
library(dplyr)
subset.poor <- subset %>% 
  filter(superstructure.condition <= 4)

states.poor <- ggplot(subset.poor, aes(x=statecode)) + geom_bar()
states.poor + theme(axis.text.x = element_text(size = 5, angle=45))
#Visibly it's clear state codes 17, 19, and 42 have many more "poor" rated bridges than others
#Illinois, Iowa, and Pennsylvania
```

```{r}
#Filtering between Illinos, Iowa and Pennsylvania
subset.poor %>% 
  filter(statecode %in% c(17, 19, 42)) %>% 
ggplot(., aes(x=yearbuilt)) + geom_bar() + xlim(1890, 1990)
#We see a lot of the poor conditioned bridges were built in the year 1900
```

```{r}
# Get county fips code
# BLS Fips code analysis
#Table with FIPS code state + county combo + BLS stat (Civilian Labor Force) + bridges
# Test new
library(blscrapeR)
county_df <- get_bls_county()
```

```{r}
#TIDY DATA with summary
subset$fips = paste(subset$statecode, subset$countycode, sep = "")

tidy.data <-  subset %>% 
  group_by(fips) %>% 
  summarise(mean.condition = mean(superstructure.condition, na.rm = T),
            mean.traffic = mean(avg.daily.traffic)) %>% 
    left_join(select(county_df, labor_force, unemployed_rate, fips), by = "fips")

head(tidy.data)
```

```{r}
#Filtering for Maricopa County, AZ
maricopa <- county_df %>% 
  filter(fips == "04013") 

bridges_maricopa <- subset %>% 
  filter(statecode == "04", 
         countycode == "013")

bridges_maricopa$fips = paste(bridges_maricopa$statecode, bridges_maricopa$countycode, sep = "")

```
